<?php



$aBrandConfig  = array(
		'oneworld365.org' => array(
					'brand_name' => 'One World 365',
					'logo_url' => 'logo_oneworld365.gif',
					'site_id' => 0,
        			'admin_email' => 'admin@oneworld365.org',
        			'website_email' => 'website@oneworld365.org',
					'website_url' => 'http://www.oneworld365.org',
					'website_name' => 'oneworld365.org',
					'website_path' => '/www/vhosts/oneworld365.org/htdocs/',
					'logo_url' => 'http://www.oneworld365.org/images/oneworld365_logo_small.png',
					'site_title' => 'One World 365',
        		    'site_info' => 'Work, Volunteer, Teach, Travel, Intern & Learn Worldwide',
					'default_placement_profile_type_id' => PROFILE_PLACEMENT,
					'default_company_profile_type_id' => PROFILE_COMPANY,
					'available_company_profile_type_id' => array(PROFILE_VOLUNTEER_PROJECT,PROFILE_COMPANY),
        			'default_categories' => array(),
					'default_activities' => array(),
					'default_countries' => array(),
					'site_categories' => array(0,2,3,4,6,7),
					'company_title' => 'Company / Organisation',
					'placement_title' => 'Placement',
					'display_cat_act_cty' => TRUE,
					'admin_website_url' => 'http://admin.oneworld365.org',
					'company_base_url' => '/company'
				),
		'gapyear365.com' => array(
					'brand_name' => 'Gap Year 365',
					'logo_url' => 'logo_gapyear365.gif',
					'site_id' => 1,
			        'admin_email' => 'info@gapyear365.com',
					'website_name' => 'gapyear365.com',
					'website_path' => '/www/vhosts/gapyear365.com/htdocs/',
				    'website_email' => 'website@gapyear365.com',
				    'website_url' => 'http://www.gapyear365.com',
					'site_title' => 'GAP YEAR 365',
        			'site_info' => 'Gap Year 365 features gap year ideas, career break & year out projects, seasonal work, teaching jobs, working holidays, summer / winter jobs, adventure holidays and tours worldwide.',
					'logo_url' => 'http://www.gapyear365.com/images/gapyear365.gif',
					'default_company_profile_type_id' => PROFILE_COMPANY,
					'default_placement_profile_type_id' => PROFILE_PLACEMENT,
					'default_categories' => array(7),
					'default_activities' => array(58),
					'default_countries' => array(),
					'site_categories' => array(7,0,2,6,4),
					'company_title' => 'Company / Organisation',
					'placement_title' => 'Placement',
				    'display_cat_act_cty' => TRUE,
					'admin_website_url' => 'http://admin.gapyear365.com',
					'company_base_url' => '/company'
				),
		'seasonaljobs365.com' => array(
					'brand_name' => 'Seasonal Jobs 365',
					'logo_url' => 'logo_seasonaljobs365.gif',
					'site_id' => 2,
			        'admin_email' => 'sales@seasonaljobs365.com',
					'website_name' => 'seasonaljobs365.com',
					'website_path' => '/www/vhosts/seasonaljobs365.com/htdocs/',
					'website_email' => 'website@seasonaljobs365.com',
				    'website_url' => 'http://dev.seasonaljobs365.com',
					'logo_url' => 'http://www.seasonaljobs365.com/images/seasonal_jobs_logo_240.gif',
					'site_title' => 'Seasonal Jobs 365',
					'site_info' => 'Seasonal Jobs 365 features seasonal work, summer jobs, winter jobs, working holidays, jobs abroad, ski jobs, holiday / tourism jobs, hotel & resort work, catering staff, hospitality jobs, care work and more',
					'default_placement_profile_type_id' => PROFILE_PLACEMENT,
					'default_company_profile_type_id' => PROFILE_SEASONALJOBS,
				   	'available_company_profile_type_id' => array(PROFILE_SEASONALJOBS),
					'default_categories' => array(6),
					'default_activities' => array(),
					'default_countries' => array(),
					'site_categories' => array(6),
					'company_title' => 'Company / Organisation',
					'placement_title' => 'Job',
				    	'display_cat_act_cty' => TRUE,
					'admin_website_url' => 'http://admin.seasonaljobs365.com',
					'company_base_url' => '/company'

				),
		'summercamp365.com' => array(
					'brand_name' => 'Summer Camp 365',
					'logo_url' => 'logo_summercamp365.gif',
					'site_id' => 3,
			        'admin_email' => 'info@summercamp365.com',
					'website_name' => 'summercamp365.com',
					'website_path' => '/www/vhosts/summercampjobs365.com/htdocs/',
					'website_email' => 'info@summercamp365.com',
				    'website_url' => 'http://www.summercamp365.com',
					'logo_url' => 'http://www.summercamp365.com/images/titles/summercamp365_logo.gif',
					'site_title' => 'Summer Camp 365',
					'site_info' => 'Summer Camp 365 features Summer Camps, Camp Jobs, International Summer Camp Staff in USA, North America and Europe',
					'default_company_profile_type_id' => PROFILE_SUMMERCAMP,
					'available_company_profile_type_id' => array(PROFILE_SUMMERCAMP),
					'default_categories' => array(3),
					'default_activities' => array(27,21),
					'default_countries' => array(71),
					'company_title' => 'Camp',
					'placement_title' => 'Summer Camp Job',
					'display_cat_act_cty' => FALSE,
					'full_desc_label' => 'Program Description',
					'admin_website_url' => 'http://admin.summercamp365.com',
					'company_base_url' => '/summer-camp'

				),
		'tefl365.com' => array(
					'brand_name' => 'Tefl 365',
					'logo_url' => 'logo_tefl365.gif',
					'site_id' => 4,
			        'admin_email' => 'info@tefl365.com',
					'website_name' => 'tefl365.com',
					'website_path' => '/www/vhosts/tefl365.com/htdocs/',
				    'website_email' => 'info@tefl365.com',
				    'website_url' => 'http://www.tefl365.com',
					'logo_url' => 'http://www.tefl365.com/images/logo_tefl365.gif',
					'site_title' => 'TEFL 365',
					'site_info' => 'TEFL 365 is a job website featuring Teaching Jobs, Language Courses, TEFL, EFL, ESL courses and schools',
					'default_company_profile_type_id' => PROFILE_TEACHING,
				    'available_company_profile_type_id' => array(PROFILE_TEACHING),
					'default_placement_profile_type_id' => PROFILE_PLACEMENT,
					'default_categories' => array(4),
					'default_activities' => array(17),
					'default_countries' => array(),
					'company_title' => 'Company / Organisation',
					'placement_title' => 'Teaching Placement',
					'display_cat_act_cty' => TRUE,
					'admin_website_url' => 'http://admin.tefl365.com',
					'company_base_url' => '/company',
					'site_categories' => array(4),
				)

);
